// "Minimal" theme — programmatic / developer-authored.
//
// Demonstrates the alternative authoring pattern to Classic's file-based
// SVGs: each card SVG is generated by a single `cardSvg(type)` helper from
// the card's type + category. Trade-offs:
//
//   File-based (Classic):     one SVG file per card. Designer-friendly,
//                              previews standalone, lots of room to draw.
//   Programmatic (Minimal):   one helper, parameterized. Coder-friendly,
//                              guarantees consistency, easy to vary
//                              algorithmically (palette swap, layout
//                              tweak, etc.) without touching 19 files.
//
// Both are first-class. The Theme type doesn't care.

import type { CardCategory, CardType } from '@/engine/cards';
import { STANDARD_DECK_COMPOSITION } from '@/engine/deck';
import { categoryOf, mileValueOf } from '@/engine/cards';
import type { Theme } from '../types';

const CATEGORY_COLOR_VAR: Readonly<Record<CardCategory, string>> = {
  mileage: 'var(--color-mileage)',
  hazard: 'var(--color-hazard)',
  remedy: 'var(--color-remedy)',
  safety: 'var(--color-safety)',
};

function labelFor(type: CardType): string {
  const v = mileValueOf(type);
  if (v !== null) return `${v}`;
  return type.replace(/^[^-]+-/, '').replace(/-/g, ' ');
}

function cardSvg(type: CardType): string {
  const category = categoryOf(type);
  const accent = CATEGORY_COLOR_VAR[category];
  const label = labelFor(type);
  const value = mileValueOf(type);
  const isMile = value !== null;
  // Mile cards: thin numeric centerpiece. Others: word label that may
  // wrap — foreignObject + HTML so the browser handles word-wrap.
  const labelMarkup = isMile
    ? `<text x="100" y="160" text-anchor="middle"
            font-family="Helvetica, Arial, sans-serif" font-weight="300"
            font-size="92" fill="var(--card-fg)">${escapeXml(label)}</text>`
    : `<foreignObject x="18" y="80" width="164" height="140">
         <div xmlns="http://www.w3.org/1999/xhtml" style="
              font-family: Helvetica, Arial, sans-serif; font-weight: 500;
              font-size: 26px; line-height: 1.05; color: var(--card-fg);
              text-align: center; text-transform: lowercase;
              letter-spacing: 0.01em;
              word-break: break-word; hyphens: auto;
              display: flex; align-items: center; justify-content: center;
              height: 100%;">
           ${escapeXml(label)}
         </div>
       </foreignObject>`;

  // Minimal frame: thin single stroke + a category-colored rule at the
  // top — each card identifiable at a glance without colored borders
  // shouting.
  return `
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 280" preserveAspectRatio="xMidYMid meet">
      <rect x="3" y="3" width="194" height="274" rx="14"
            fill="var(--card-bg)" stroke="var(--card-fg)" stroke-width="1.5"/>
      <rect x="14" y="14" width="172" height="4" fill="${accent}"/>
      ${labelMarkup}
      <text x="100" y="248" text-anchor="middle"
            font-family="Helvetica, Arial, sans-serif" font-size="11"
            fill="var(--card-fg)" opacity="0.55"
            style="letter-spacing: 0.18em;">${category.toUpperCase()}</text>
    </svg>
  `.trim();
}

function buildAllCards(): Record<CardType, string> {
  const out: Partial<Record<CardType, string>> = {};
  for (const [type] of STANDARD_DECK_COMPOSITION) {
    out[type] = cardSvg(type);
  }
  return out as Record<CardType, string>;
}

function escapeXml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

const back = `
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 280" preserveAspectRatio="xMidYMid meet">
    <rect x="3" y="3" width="194" height="274" rx="14"
          fill="var(--card-back-a)" stroke="var(--card-back-fg)" stroke-width="1.5"/>
    <line x1="40" y1="100" x2="160" y2="100" stroke="var(--card-back-fg)" stroke-width="1.5"/>
    <line x1="40" y1="180" x2="160" y2="180" stroke="var(--card-back-fg)" stroke-width="1.5"/>
    <text x="100" y="148" text-anchor="middle"
          font-family="Helvetica, Arial, sans-serif" font-weight="300"
          font-size="32" letter-spacing="0.2em" fill="var(--card-back-fg)">MB</text>
  </svg>
`.trim();

export const minimalTheme: Theme = {
  id: 'minimal',
  name: 'Minimal',
  cards: buildAllCards(),
  back,
  cssVars: {
    '--card-bg': '#ffffff',
    '--card-fg': '#1a1a1a',
    '--color-mileage': '#1f6feb',
    '--color-hazard': '#cf222e',
    '--color-remedy': '#1a7f37',
    '--color-safety': '#bf8700',
    '--card-back-a': '#1a1a1a',
    '--card-back-b': '#222',
    '--card-back-frame': '#888',
    '--card-back-fg': '#eaeaea',
  },
};
